---
ID: "e03c6aa7-be0b-4ffc-8ebb-6db8fa58b5b4"
Parent: "091e6e59-b7e5-4eda-b742-ad432a30a34d"
Template: "9f7eb765-4566-4dd5-b74f-8bba6a27ba17"
Path: "/sitecore/content/industry-verticals/forma-lux/Settings/Retail Site Settings"
SharedFields:
- ID: "bd13b584-36a1-4c4e-aa1c-b4689ee2fae8"
  Hint: CustomCSS
  Value: |
    --color-foreground: #c125a4;
    --color-foreground-light: #5a4636;
    --color-foreground-muted: #a68a6d;
    --color-background: #fff8f3;
    --color-background-accent: #fbe4d6;
    --color-background-muted: #f4e9e2;
    --color-background-muted-light: #cbb8a6;
    --color-background-muted-dark: #9e8c7a;
    --color-background-surface: #fff3e8;
    --color-accent: #811378;
    --color-success: #6bbf59;
    --color-danger: #d95f5f;
    --color-border: #e6d8c8;
    --font-heading: 'Pacifico', cursive;
    --font-body: 'Nunito', sans-serif;
    --radius-base: 0rem;
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5bc63866-52f8-4565-8554-d004ffc169bb"
- ID: "f4f80dc4-7985-4bba-a11e-4daebba94481"
  Hint: ThemeDefaults
  Value: |
    --color-foreground: #1e1e1e;
    --color-foreground-light: #505050;
    --color-foreground-muted: #9f9f9f;
    --color-background: #fff;
    --color-background-accent: #faf3ea;
    --color-background-muted: #f7f7f7;
    --color-background-muted-light: #7a7a7a;
    --color-background-muted-dark: #666;
    --color-background-surface: #fafafa;
    --color-accent: #c1a25f;
    --color-success: #2ec1ac;
    --color-danger: #e97171;
    --color-border: #e8e8e8;
    --font-heading: 'Manrope', sans-serif;
    --font-body: 'Manrope', sans-serif;
    --radius-base: 0.5rem;
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "38c79e1a-489b-431d-b04e-aefea3c09438"
      Hint: FontOptions
      Value: |
        [
          {
            "label": "Sans Serif",
            "suffix": ", sans-serif",
            "fonts": [
              {
                "name": "Anton",
                "link": "https://fonts.googleapis.com/css2?family=Anton&display=swap"
              },
              {
                "name": "Bebas Neue",
                "link": "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
              },
              {
                "name": "Inter",
                "link": "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
              },
              {
                "name": "Lato",
                "link": "https://fonts.googleapis.com/css2?family=Lato:wght@100..900&display=swap"
              },
              {
                "name": "Manrope",
                "link": "https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
              },
              {
                "name": "Montserrat",
                "link": "https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap"
              },
              {
                "name": "Mulish",
                "link": "https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap"
              },
              {
                "name": "Noto Sans",
                "link": "https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
              },
              {
                "name": "Nunito",
                "link": "https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000&display=swap"
              },
              {
                "name": "Open Sans",
                "link": "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300..800&display=swap"
              },
              {
                "name": "Oswald",
                "link": "https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
              },
              {
                "name": "Poppins",
                "link": "https://fonts.googleapis.com/css2?family=Poppins:wght@100..900&display=swap"
              },
              {
                "name": "Roboto",
                "link": "https://fonts.googleapis.com/css2?family=Roboto:wght@100..900&display=swap"
              },
              {
                "name": "Rubik",
                "link": "https://fonts.googleapis.com/css2?family=Rubik:wght@300..900&display=swap"
              }
            ]
          },
          {
            "label": "Serif",
            "suffix": ", serif",
            "fonts": [
              {
                "name": "Abril Fatface",
                "link": "https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap"
              },
              {
                "name": "Cormorant",
                "link": "https://fonts.googleapis.com/css2?family=Cormorant:wght@300..700&display=swap"
              },
              {
                "name": "Libre Baskerville",
                "link": "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400..700;1,400..700&display=swap"
              },
              {
                "name": "Lora",
                "link": "https://fonts.googleapis.com/css2?family=Lora:wght@400..700&display=swap"
              },
              {
                "name": "Merriweather",
                "link": "https://fonts.googleapis.com/css2?family=Merriweather:wght@300..900&display=swap"
              },
              {
                "name": "Playfair Display",
                "link": "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400..900&display=swap"
              },
              {
                "name": "Roboto Serif",
                "link": "https://fonts.googleapis.com/css2?family=Roboto+Serif:wght@100..900&display=swap"
              }
            ]
          },
          {
            "label": "Monospace",
            "suffix": ", monospace",
            "fonts": [
              {
                "name": "Fira Code",
                "link": "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"
              },
              {
                "name": "Roboto Mono",
                "link": "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100..700&display=swap"
              },
              {
                "name": "Source Code Pro",
                "link": "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@200..900&display=swap"
              },
              {
                "name": "Space Mono",
                "link": "https://fonts.googleapis.com/css2?family=Space+Mono:wght@400..700&display=swap"
              }
            ]
          },
          {
            "label": "Display",
            "suffix": ", cursive",
            "fonts": [
              {
                "name": "Great Vibes",
                "link": "https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap"
              },
              {
                "name": "Pacifico",
                "link": "https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
              },
              {
                "name": "Satisfy",
                "link": "https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
              }
            ]
          }
        ]
        
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1b87be1a-a0a0-491f-a672-eb8892eab406"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\INIwVuCCf0fzziGGBdz0UepKJ8K6him7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251205T215627Z
